name: i18n
description: Simple i18n solution for dart and flutter. Uses code generation to generate translations as dart classes. Efficient and works with autocomplete!
version: 2.1.0
homepage: https://github.com/MohiuddinM/i18n

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"

dependencies:
  build: ^1.6.2
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^0.4.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^1.11.1
  build_web_compilers: ^2.16.3
  # pedantic: ^1.0.0
  test: ^1.16.2
